version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ndisFP2019
      
  django:
    build: ./backend/ndis_calculator
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ndis_calculator:/app/ndis_calculator
    command: ["ls","-lR"]
    command: ["pwd"]
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
