version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ndisFP2019
      
  django:
    build: 
        context: ./backend/ndis_calculator
        dockerfile: Dockerfile-CI	
    ports:
      - "8000:8000"
    command: >
      sh -c "pwd &&
             ls -lR &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    links:
      - db
    depends_on:
      - db
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile-CI
    ports:
      - "3000:3000"
