version: "3.7"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --init-file /app/ndis_calculator/init.sql
    restart: always
    volumes:
      - ./backend/ndis_calculator/init.sql:/app/ndis_calculator/init.sql
      - ndis-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ndisFP2019

  django:
    build:
      context: ./backend/ndis_calculator
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_DJANGO_PORT}:8000"
    command: >
      sh -c "pwd &&
          ls -lR &&
          ./entrypoint.sh"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_REACT_PORT}:3000"

volumes:
  ndis-datavolume:
