version: "3.7"

services:
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: ndis
      MYSQL_ROOT_PASSWORD: ndisFP2019
      MYSQL_ROOT_HOST: "%"

  django:
    build:
      context: ./backend/ndis_calculator
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_DJANGO_PORT}:8000"
    command: >
      sh -c "pwd &&
          ls -lR &&
          ./entrypoint.sh"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_REACT_PORT}:3000"
    volumes:
      - npm-cache:/root/.npm

volumes:
  db-data:
  npm-cache:
    external: true
