version: "3.7"

services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ndis
      MYSQL_ROOT_PASSWORD: ndisFP2019

  django:
    build:
      context: ./backend/ndis_calculator
      dockerfile: Dockerfile-CI.test
    ports:
      - "${DOCKER_DJANGO_PORT}:8000"
    command: >
      sh -c "pwd &&
          ls -lR &&
          ./entrypoint-test.sh"
    depends_on:
      - db
