version: "3.7"

services:
  db:
    image: mysql/mysql-server:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: ndis
      MYSQL_ROOT_PASSWORD: ndisFP2019
      MYSQL_ROOT_HOST: "%"

  django:
    build: ./backend/ndis_calculator
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ndis_calculator:/app/ndis_calculator
    working_dir: /app/ndis_calculator/
    command: sh entrypoint.sh
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend/

volumes:
  db-data: {}
