version: "3.7"

services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./backend/ndis_calculator/sql:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ndisFP2019

  django:
    build:
      context: ./backend/ndis_calculator
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_DJANGO_PORT}:8000"
    command: >
      sh -c "pwd &&
          ls -lR &&
          ./entrypoint.sh"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-CI
    ports:
      - "${DOCKER_REACT_PORT}:3000"

volumes:
  db-data: {}
