version: "3.7"

services:
  jenkins5:
    build: build Jenkins-Dockerfile
    restart: always
    privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:
