openapi: 3.0.2

info:
  title: ndis_calculator
  version: 1.0.1

servers:
  - url: http://localhost:8000/api/v1
    description: Development server (local)

paths:
  /participants/{participant_id}/plans:
    get:
      tags:
        - plan
      summary: Retrieve list of all plans of a specific participant
      description: Retrieve list of all plans of a specific participant, both generated and non-generated
      parameters:
        - $ref: "#/components/parameters/ParticipantId"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Plan"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"

    post:
      tags:
        - plan
      summary: Create a plan based on an existing plan
      description: Create a plan based on an existing plan of a specific participant, labeled non-generated in the backend
      parameters:
        - $ref: "#/components/parameters/ParticipantId"
      responses:
        "201":
          description: success
          content:
            application/json:
              schema:
                type: integer
                description: plan id
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"

  /registration-groups:
    get:
      tags:
        - registration group
      summary: Retrieves list of registration groups
      description: Retrieves all registration groups
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RegistrationGroup"
  /support-groups:
    get:
      tags:
        - support group
      summary: Retrieves list of support groups and their support categories
      description: Retrieves list of support groups and their support categories in database order
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportGroup"
  /support-items:
    get:
      tags:
        - support item
      summary: Retrieves list of support items
      description: Retrieves list of support items based on filter. The backend will retrieve the appropriate price based on the postcode.
      parameters:
        - name: birth-year
          in: query
          schema:
            type: integer
          required: true
        - name: postcode
          in: query
          schema:
            type: integer
          required: true
        - name: registration-group-id
          in: query
          schema:
            type: integer
        - name: support-category-id
          in: query
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportItemGroup"
  /support-item-groups:
    get:
      tags:
        - support item group
      summary: Retrieves list of support item groups (more simple english, less clutter than support_item)
      description: Retrieves list of support item groups based on filter, The backend will retrieve the default national price for simplicity
      parameters:
        - name: registration-group-id
          in: query
          schema:
            type: integer
          required: true
        - name: support-group-id
          in: query
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportItem"
  /plan-categories/{plan_category_id}/plan-items/:
    post:
      tags:
        - plan item
      summary: Create a plan item for a participant's plan.
      description: Create a plan item for a plan in one of his existing goals under the correct category.
      parameters:
        - $ref: "#/components/parameters/PlanCategoryId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                supportItemGroup:
                  type: integer
                  example: 144
                quantity:
                  type: number
                  example: 10
                priceActual:
                  type: number
                  example: 120.22
                name:
                  type: string
                  example: wheelchair
                frequencyPerYear:
                  type: integer
                  example: 52
      responses:
        "201":
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  planCategory:
                    type: integer
                    example: 1
                  supportItemGroup:
                    type: integer
                    example: 144
                  quantity:
                    type: number
                    example: 10
                  priceActual:
                    type: number
                    example: 120.22
                  name:
                    type: string
                    example: wheelchair
                  frequencyPerYear:
                    type: integer
                    example: 52
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"

components:
  schemas:
    SupportGroup:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Capital"
        supportCategories:
          type: array
          items:
            $ref: "#/components/schemas/SupportCategory"

    SupportCategory:
      type: object
      properties:
        id:
          type: integer
          example: 16
        name:
          type: string
          example: Improved life choices

    SupportItem:
      type: object
      properties:
        id:
          type: integer
          example: 717
        number:
          type: string
          example: "15_001_0118_1_3"
        name:
          type: string
          example: Capacity Building Supports For Early Childhood Interventions - Psychology
        description:
          type: string
          example: Capacity building supports, including key worker, to assist a child with developmental delay and/or disability and their family/carers in home, community and early childhood education settings, to work towards increased functional independence and social participation. To be delivered by a Psychologist.
        unit:
          type: string
          example: H
        price:
          type: number
          example: 243.83
    SupportItemGroup:
      type: object
      properties:
        id:
          type: integer
          example: 717
        name:
          type: string
          example: Capacity Building Supports For Early Childhood Interventions - Psychology
        description:
          type: string
          example: Capacity building supports, including key worker, to assist a child with developmental delay and/or disability and their family/carers in home, community and early childhood education settings, to work towards increased functional independence and social participation. To be delivered by a Psychologist.
        unit:
          type: string
          example: H
        price:
          type: number
          example: 243.83
    RegistrationGroup:
      type: object
      properties:
        id:
          type: integer
          example: 41
        name:
          type: string
          example: "Early Intervention Supports For Early Childhood"

    Plan:
      type: object
      properties:
        id:
          type: integer
          example: 1
        startDate:
          type: string
          example: 01/01/2019
        endDate:
          type: string
          example: 02/01/2019
        generated:
          type: boolean
          example: false

  responses:
    Unauthenticated:
      description: Unauthenticated
    Unauthorised:
      description: Unauthorised to access this resource
    BadRequest:
      description: Bad Request

  parameters:
    ParticipantId:
      name: participant_id
      in: path
      description: participant Id
      required: true
      schema:
        type: integer

    PlanId:
      name: plan_id
      in: path
      description: plan Id
      required: true
      schema:
        type: integer

    PlanCategoryId:
      name: plan_category_id
      in: path
      description: plan category Id
      required: true
      schema:
        type: integer
