openapi: 3.0.2
info:
  title: NDIS Financial Planner
  version: 1.1.0
servers:
  - url: http://localhost:8000/api/v1
    description: Development server (local)

paths:
  /plans:
    get:
      security:
        - JWT: []
      tags:
        - Plan
      summary: Retrieve all plans of the request's participant
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/Plan"
                    - type: object
                      properties:
                        id:
                          type: integer
                        planCategories:
                          type: array
                          items:
                            allOf:
                              - $ref: "#/components/schemas/PlanCategory"
                              - type: object
                                properties:
                                  id:
                                    type: integer
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"

    post:
      security:
        - JWT: []
      tags:
        - Plan
      summary: Create a plan
      description: Create a plan from start date, end date and a budgets array where each element is an array in the form of (supportCategoryId, budget)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Plan"
                - type: object
                  properties:
                    supportCategories:
                      type: array
                      items:
                        type: object
                        properties:
                          supportCategory:
                            type: integer
                          budget:
                            type: number
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Plan"
                  - type: object
                    properties:
                      id:
                        type: integer
                      planCategories:
                        type: array
                        items:
                          allOf:
                            - $ref: "#/components/schemas/PlanCategory"
                            - type: object
                              properties:
                                id:
                                  type: integer
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"

  /plans/{plan_id}:
    patch:
      security:
        - JWT: []
      tags:
        - Plan
      summary: Update a single plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Plan"
                - type: object
                  properties:
                    planCategories:
                      type: array
                      items:
                        type: object
                        properties:
                          planCategory:
                            type: integer
                          budget:
                            type: number
      parameters:
        - $ref: "#/components/parameters/PlanId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Plan"
                  - type: object
                    properties:
                      id:
                        type: integer
                      planCategories:
                        type: array
                        items:
                          $ref: "#/components/schemas/PlanCategory"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

  /plans/{plan_id}/categories/{plan_category_id}/groups:
    get:
      security:
        - JWT: []
      tags:
        - Plan Item Group
      summary: Retrieve all plan item groups from a plan category
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PlanItemGroup"
                properties:
                  id:
                    type: integer
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

    post:
      security:
        - JWT: []
      tags:
        - Plan Item Group
      summary: Create a plan item group in a plan category
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlanItemGroup"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PlanItemGroup"
                properties:
                  id:
                    type: integer
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

  /plans/{plan_id}/categories/{plan_category_id}/groups/{plan_item_group_id}:
    patch:
      security:
        - JWT: []
      tags:
        - Plan Item Group
      summary: Update a plan item group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: "Something items"
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      security:
        - JWT: []
      tags:
        - Plan Item Group
      summary: Delete a plan item group
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

  ? /plans/{plan_id}/categories/{plan_category_id}/groups/{plan_item_group_id}/items
  : get:
      security:
        - JWT: []
      tags:
        - Plan Item
      summary: Retrieve all plan items from a plan item group
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PlanItem"
                properties:
                  id:
                    type: integer
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

    post:
      security:
        - JWT: []
      tags:
        - Plan Item
      summary: Create a plan item in a plan item group
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlanItem"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PlanItem"
                properties:
                  id:
                    type: integer
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

  ? /plans/{plan_id}/categories/{plan_category_id}/groups/{plan_item_group_id}/items/{plan_item_id}
  : patch:
      security:
        - JWT: []
      tags:
        - Plan Item
      summary: Update a plan item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: wheelchair
                priceActual:
                  type: number
                  example: 120.22
                startDate:
                  type: string
                  example: 20/01/2019
                endDate:
                  type: string
                  example: 10/02/2020
                allDay:
                  type: boolean
                  example: false
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
        - $ref: "#/components/parameters/PlanItemId"
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      security:
        - JWT: []
      tags:
        - Plan Item
      summary: Delete a plan item
      parameters:
        - $ref: "#/components/parameters/PlanId"
        - $ref: "#/components/parameters/PlanCategoryId"
        - $ref: "#/components/parameters/PlanItemGroupId"
        - $ref: "#/components/parameters/PlanItemId"
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "401":
          $ref: "#/components/responses/Unauthenticated"
        "403":
          $ref: "#/components/responses/Unauthorised"
        "404":
          $ref: "#/components/responses/NotFound"

  /support-groups:
    get:
      tags:
        - Support Group
      summary: Retrieves list of support groups and their support categories
      description: Retrieves list of support groups and their support categories in database order
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportGroup"

  /support-item-groups:
    get:
      tags:
        - Support Item Group
      summary: Retrieves list of support item groups (more simple english, less clutter than support_item)
      description: Retrieves list of support item groups based on filter, The backend will retrieve the default national price for simplicity
      parameters:
        - name: registration-group-id
          in: query
          schema:
            type: integer
          required: true
        - name: support-category-id
          in: query
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportItem"

  /support-items:
    get:
      tags:
        - Support Item
      summary: Retrieves list of support items
      description: Retrieves list of support items based on filter. The backend will retrieve the appropriate price based on the postcode.
      parameters:
        - name: birth-year
          in: query
          schema:
            type: integer
          required: true
        - name: postcode
          in: query
          schema:
            type: integer
          required: true
        - name: registration-group-id
          in: query
          schema:
            type: integer
        - name: support-category-id
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SupportItemGroup"

  /registration-groups:
    get:
      tags:
        - Registration Group
      summary: Retrieves list of registration groups
      description: Retrieves all registration groups
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RegistrationGroup"

components:
  schemas:
    Plan:
      type: object
      properties:
        name:
          type: string
          example: "My first plan"
        ndis_number:
          type: integer
          # example: 0123456789
        startDate:
          type: string
          example: 01/01/2019
        endDate:
          type: string
          example: 02/01/2019

    PlanCategory:
      type: object
      properties:
        plan:
          type: integer
        supportCategory:
          type: integer
        budget:
          type: number

    PlanItemGroup:
      type: object
      properties:
        planCategory:
          type: integer
          example: 24
        supportItemGroup:
          type: integer
          example: 42
        name:
          type: string

    PlanItem:
      type: object
      properties:
        planitemGroup:
          type: integer
          example: 3117
        name:
          type: string
          example: wheelchair
        priceActual:
          type: number
          example: 120.22
        startDate:
          type: string
          example: 20/01/2019
        endDate:
          type: string
          example: 10/02/2020
        allDay:
          type: boolean
          example: false

    SupportGroup:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Capital"
        supportCategories:
          type: array
          items:
            $ref: "#/components/schemas/SupportCategory"

    SupportCategory:
      type: object
      properties:
        id:
          type: integer
          example: 16
        name:
          type: string
          example: Improved life choices

    SupportItemGroup:
      type: object
      properties:
        id:
          type: integer
          example: 717
        name:
          type: string
          example: Capacity Building Supports For Early Childhood Interventions - Psychology
        description:
          type: string
          example: Capacity building supports, including key worker, to assist a child with developmental delay and/or disability and their family/carers in home, community and early childhood education settings, to work towards increased functional independence and social participation. To be delivered by a Psychologist.
        unit:
          type: string
          example: H
        price:
          type: number
          example: 243.83

    SupportItem:
      type: object
      properties:
        id:
          type: integer
          example: 717
        number:
          type: string
          example: "15_001_0118_1_3"
        name:
          type: string
          example: Capacity Building Supports For Early Childhood Interventions - Psychology
        description:
          type: string
          example: Capacity building supports, including key worker, to assist a child with developmental delay and/or disability and their family/carers in home, community and early childhood education settings, to work towards increased functional independence and social participation. To be delivered by a Psychologist.
        unit:
          type: string
          example: H
        price:
          type: number
          example: 243.83

    RegistrationGroup:
      type: object
      properties:
        id:
          type: integer
          example: 41
        name:
          type: string
          example: "Early Intervention Supports For Early Childhood"

  responses:
    NoContent:
      description: No Content
    Unauthenticated:
      description: Unauthenticated
    Unauthorised:
      description: Unauthorised to access this resource
    BadRequest:
      description: Bad Request
    NotFound:
      description: Resource not found

  parameters:
    ParticipantId:
      name: participant_id
      in: path
      required: true
      schema:
        type: integer

    PlanId:
      name: plan_id
      in: path
      required: true
      schema:
        type: integer

    PlanCategoryId:
      name: plan_category_id
      in: path
      required: true
      schema:
        type: integer

    PlanItemGroupId:
      name: plan_item_group_id
      in: path
      required: true
      schema:
        type: integer

    PlanItemId:
      name: plan_item_id
      in: path
      required: true
      schema:
        type: integer

  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
