name: Publish Docker

on:
  push:
    branches:
      - develop

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BRANCH_FILTER: "develop"
  DOCKER_NAMESPACE: "nevrending"
  DOCKER_IMAGE_NAME: "lifeplan"

jobs:
  django:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
    env:
      DOCKER_IMAGE_TAG: "django-latest"
    steps:
      - uses: actions/checkout@master
      - name: Pull previous image for cache
        run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - name: Build and Publish to Docker Hub
        uses: pangzineng/Github-Action-One-Click-Docker@master
        with:
          args: "-f backend/ndis_calculator/prod.Dockerfile ./backend/ndis_calculator"

  frontend:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
    env:
      DOCKER_IMAGE_TAG: "frontend-latest"
    steps:
      - uses: actions/checkout@master
      - name: Pull previous image for cache
        run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - name: Build and Publish to Docker Hub
        uses: pangzineng/Github-Action-One-Click-Docker@master
        with:
          args: "-f frontend/prod.Dockerfile ./frontend"
