name: Lifeplan

on:
  push:
    branches-ignore:
      - master
      - develop
  # pull_request:
  #   branches:
  #     - master
  #     - develop

jobs:
  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7]
        mysql-version: ["8.0"]

    services:
      mysql:
        image: mysql/mysql-server:${{ matrix.mysql-version }}
        env:
          MYSQL_DATABASE: ndis
          MYSQL_USER: ndis
          MYSQL_PASSWORD: ndisFP2019
          MYSQL_ROOT_PASSWORD: ndisFP2019
          MYSQL_ROOT_HOST: %
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -pndisFP2019 -e "SHOW DATABASES"
      - name: Install build dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
            default-libmysqlclient-dev \
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend/ndis_calculator
          pip install -r requirements.txt
      # - name: Shutdown Ubuntu MySQL (SUDO)
      #   run: sudo service mysql stop
      # - name: Set up MySQL
      #   uses: mirromutth/mysql-action@v1.1
      #   with:
      #     mysql version: ${{ matrix.mysql-version }}
      #     mysql database: 'ndis'
      #     mysql root password: 'ndisFP2019'
      # - name: Wait for MySQL to be ready
      #   run: |
      #     until nc -z 127.0.0.1 3306; do sleep 1; echo "Waiting for MySQL to be ready..."; done
      - name: Prepare for tests
        run: |
          cd backend/ndis_calculator
          python manage.py makemigrations --no-input
          python manage.py migrate --no-input
          python manage.py collectstatic --no-input
          python manage.py loaddata budgeting/fixtures/*
        env:
          DATABASE_HOST: 127.0.0.1
      - name: Run tests
        run: |
          manage.py test budgeting

  frontend:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
        node-version: [13]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: List packages
        run: |
          cat frontend/package.json
      - name: Install dependencies
        run: |
          yarn --cwd frontend/
      - name: Build production assets
        run: |
          yarn --cwd frontend/ build
      - name: Run tests
        run: |
          CI=true yarn --cwd frontend/ test
